nombre_array = [1, "ey", 15]
print(nombre_array[:])
print("en concreto")
print(nombre_array[0])
print("desde el final en negativo")
print(nombre_array[-1])
print("acceder a diferentes valores excluido el ultimo")
print(nombre_array[0:1])
print("el ultimo numero escrito no cuenta")
print("abreviado, incluyendo desde el principio es")
print(nombre_array[:2])
print("al reves")
print(nombre_array[1:])
print("agregar elementos con append")
nombre_array.append("nuevo")
print(nombre_array[:], "Agrega al final")
print("agregar en un indice en concreto")
nombre_array.insert(2, "Siguiente nuevo")
print(nombre_array[:])
print("agregar varios elementos, como concatenar un array al final del primero")
nombre_array.extend(["Roots", 10, "Weed"])
print(nombre_array[:])
print("Saber el indice de un objeto")
print("indice de weed", nombre_array.index("Weed"))
print("saber si existe un objeto")
print("Roots" in nombre_array)
print("Ambrosio" in nombre_array)
print("eliminar elemento")
nombre_array.remove(1)
print(nombre_array[:])
print("Eliminar ultimo elemento")
nombre_array.pop()
print(nombre_array[:])
print("Agregar otra lista")
lista2 = [10, "Oy", "CXD"]
lista3 = nombre_array + lista2
print(lista3)
print("repetir lista")
lista3 *= 3
print(lista3)
